// Generated by https://quicktype.io
export interface FetchAllRuletaResponse {
    count:    number;
    next:     null;
    previous: null;
    results:  SmallRuleta[];
}

export interface SmallRuleta {
    name: string;
    url:  string;
}


export interface Ruleta {
    id: string;
    name: string;
    pic: string;
}